spring.application.name=Application
# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# H2 Database for Development (persisted to disk)
spring.datasource.url=jdbc:h2:file:./data/onlinelearning;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# JPA/Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
# Connection Pool Properties
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000

#email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=learningonline009@gmail.com
spring.mail.password=oebkfxzovugoguzu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.timeout=5000

#debug
logging.level.org.springframework.security=DEBUG

#Upload file
storage.location=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB