spring.application.name=Application
# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
# SQL Server Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=OnlineLearning;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=123456
# JPA/Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
# Connection Pool Properties
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000

#email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=learningonline009@gmail.com
spring.mail.password=oebkfxzovugoguzu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.timeout=5000

#debug
logging.level.org.springframework.security=DEBUG

#Upload file
storage.location=uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB